### PR TITLE
Added feature to create user.

### PR DESCRIPTION
**Pull request by edmargomes**
We are using in project with Ambidex and Drupal 7.

Thanks @sebas5384 for help me in this code.

### CODE REVIEW

**Comment by DanielOchoa** [comment]
Thanks!

**Comment by DanielOchoa** [comment]
@edmargomes I reverted the pull request. Could you also be so kind as to write a test case as well?

Sorry, I haven't had my coffee yet so I merged it without looking at it. Let me know if you need direction.

**Comment by edmargomes** [comment]
No problem, I really need direction to create the test .Can you help-me?

**Comment by DanielOchoa** [comment]
Yes I can. I can't right now but I'll reply here with what you need later
today.

**Comment by DanielOchoa** [comment]
@edmargomes No worries, I added the test. If you look at commit b4d3d65c03712612d4ddfe178755a32c2287bcdd you can see how. Basically, I used nock to mock the request, and mapped it to a response from `nock-responses.json`. While it does not test the correct params are being passed (and I feel it shouldn't, that's Drupal's domain) it tests that the correct url is being hit with the right type of request.

**Comment by DanielOchoa** [comment]
@edmargomes I just noticed your addition is not documented. Could you open a new pull requests to add it to the README?

**Pull request merged**
